<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit21b07db21188914a4045231f59c4b38b
{
    public static $prefixLengthsPsr4 = array (
        'K' => 
        array (
            'Kuya\\CruzDentalClinicWeb\\' => 25,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Kuya\\CruzDentalClinicWeb\\' => 
        array (
            0 => __DIR__ . '/../..' . '/src',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit21b07db21188914a4045231f59c4b38b::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit21b07db21188914a4045231f59c4b38b::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit21b07db21188914a4045231f59c4b38b::$classMap;

        }, null, ClassLoader::class);
    }
}
